name: sessionmanager
region: nyc
services:
  - name: sessionmanager
    github:
      repo: HusseinJX/sessionmanager
      branch: master
      deploy_on_push: true
    dockerfile_path: server/Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
